# MIT License
# Copyright (c) 2024 Maharshi Soni

"""Base class and factory for LLM providers."""

from __future__ import annotations

import abc
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from testpilot.models import FunctionInfo, TestCase


class LLMProvider(abc.ABC):
    """Abstract base class for LLM providers.

    An LLM provider can optionally enhance test generation by producing
    more context-aware test cases, assertions, or docstrings.
    """

    @property
    @abc.abstractmethod
    def name(self) -> str:
        """Human-readable provider name."""
        ...

    @abc.abstractmethod
    def is_available(self) -> bool:
        """Return True if the provider is configured and reachable."""
        ...

    @abc.abstractmethod
    def enhance_test_cases(
        self,
        func: FunctionInfo,
        existing_cases: list[TestCase],
    ) -> list[TestCase]:
        """Use the LLM to improve or extend the given test cases.

        Parameters
        ----------
        func:
            The function under test.
        existing_cases:
            Test cases already generated by the strategy engine.

        Returns
        -------
        list[TestCase]
            Enhanced or additional test cases.
        """
        ...

    @abc.abstractmethod
    def generate_assertion(
        self,
        func: FunctionInfo,
        test_case: TestCase,
    ) -> str:
        """Generate a specific assertion expression for a test case.

        Parameters
        ----------
        func:
            The function under test.
        test_case:
            The test case needing an assertion.

        Returns
        -------
        str
            A Python assertion expression (e.g. ``"assert result == 42"``).
        """
        ...


def get_provider(provider_name: str, **kwargs: str) -> LLMProvider:
    """Factory function to instantiate an LLM provider by name.

    Parameters
    ----------
    provider_name:
        One of ``"none"``, ``"claude_cli"``, ``"api"``.
    **kwargs:
        Provider-specific configuration (e.g. ``api_key``).

    Returns
    -------
    LLMProvider
        The requested provider instance.

    Raises
    ------
    ValueError
        If the provider name is not recognised.
    """
    from testpilot.providers.none_provider import NoneProvider
    from testpilot.providers.claude_cli import ClaudeCLIProvider
    from testpilot.providers.api_provider import APIProvider

    providers: dict[str, type[LLMProvider]] = {
        "none": NoneProvider,
        "claude_cli": ClaudeCLIProvider,
        "api": APIProvider,
    }

    cls = providers.get(provider_name)
    if cls is None:
        raise ValueError(
            f"Unknown provider '{provider_name}'. "
            f"Choose from: {', '.join(providers)}"
        )
    return cls(**kwargs)  # type: ignore[call-arg]
