# MIT License
# Copyright (c) 2024 Maharshi Soni

"""pytest plugin for TestPilot AI.

Registers ``--testpilot-generate`` option that auto-generates tests for
discovered source modules before the test session runs.

Usage:
    pytest --testpilot-generate src/
"""

from __future__ import annotations

from pathlib import Path
from typing import Any

import pytest

from testpilot.analyzer import analyze_module
from testpilot.generator import generate_test_suite
from testpilot.models import TestPilotConfig


def pytest_addoption(parser: Any) -> None:
    """Add TestPilot command-line options to pytest."""
    group = parser.getgroup("testpilot", "TestPilot AI test generation")
    group.addoption(
        "--testpilot-generate",
        action="store",
        default=None,
        metavar="PATH",
        help="Generate tests for Python files under PATH before running.",
    )
    group.addoption(
        "--testpilot-output",
        action="store",
        default="tests/generated",
        metavar="DIR",
        help="Directory for generated test files (default: tests/generated).",
    )


def pytest_configure(config: Any) -> None:
    """Register the TestPilot marker."""
    config.addinivalue_line(
        "markers",
        "testpilot: marks tests as auto-generated by TestPilot AI",
    )


def pytest_sessionstart(session: Any) -> None:
    """Generate tests if --testpilot-generate was passed."""
    target = session.config.getoption("testpilot_generate")
    if target is None:
        return

    target_path = Path(target)
    output_dir = Path(session.config.getoption("testpilot_output"))
    output_dir.mkdir(parents=True, exist_ok=True)

    tp_config = TestPilotConfig(
        target_path=target_path,
        output_dir=output_dir,
    )

    py_files: list[Path] = []
    if target_path.is_file():
        py_files.append(target_path)
    elif target_path.is_dir():
        py_files.extend(target_path.rglob("*.py"))

    for src_file in py_files:
        if src_file.name.startswith("test_") or src_file.name.endswith("_test.py"):
            continue
        analysis = analyze_module(src_file)
        suite = generate_test_suite(analysis, tp_config)
        if suite.generated_code:
            out_file = output_dir / f"test_{src_file.stem}_generated.py"
            out_file.write_text(suite.generated_code, encoding="utf-8")
